name: Publish to PyPI

on: ["push", "pull_request"]

defaults:
  run:
    shell: bash

jobs:
  packages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Get tags
      run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

    - name: Install build tools
      run: |
        python -m pip install --upgrade pip wheel setuptools setuptools_scm build twine check-manifest

    - name: Build binary wheel
      run: python -m build --sdist --wheel . --outdir dist

    - name: CheckFiles
      run: >
        check-manifest
        && ls dist

    - name: Test wheels
      run: |
        cd dist && python -m pip install windrose*.whl
        python -m twine check *

    - name: Publish a Python distribution to PyPI
      if: ${{ github.event_name == 'release' }}
      uses: pypa/gh-action-pypi-publish@v1.6.4
      with:
        user: __token__
        password: ${{ secrets.PYPI_PASSWORD }}
